export const USER_PROBLEMS_SUCCESS = "USER_PROBLEMS_SUCCESS";
export const USER_PROBLEMS_REQUEST = "USER_PROBLEMS_REQUEST";
export const USER_PROBLEMS_FAIL = "USER_PROBLEMS_FAIL";
export const SORT_PROBLEMS_ARRAY = "SORT_PROBLEMS_ARRAY";