export const Tags = [
  { label: "math", value: "Math" },
  { label: "greedy", value: "Greedy" },
  { label: "implementation", value: "Implementation" },
  { label: "dp", value: "Dynamic Programming" },
  { label: "data structures", value: "Data Structures" },
  { label: "constructive algorithms", value: "Constructive Algorithms" },
  { label: "sortings", value: "Sortings" },
  { label: "binary search", value: "Binary Search" },
  { label: "dfs and similar", value: "DFS And Similar" },
  { label: "*special", value: "Special" },
  { label: "trees", value: "Trees" },
  { label: "combinatorics", value: "Combinatorics" },
  { label: "bitmasks", value: "Bitmasks" },
  { label: "number theory", value: "Number Theory" },
  { label: "strings", value: "Strings" },
  { label: "two pointers", value: "Two Pointers" },
  { label: "dsu", value: "DSU" },
  { label: "geometry", value: "Geometry" },
  { label: "probabilities", value: "Probabilities" },
  { label: "divide and conquer", value: "Divide And Conquer" },
  { label: "shortest paths", value: "Shortest Paths" },
  { label: "games", value: "Games" },
  { label: "hashing", value: "Hashing" },
  { label: "interactive", value: "Interactive" },
  { label: "flows", value: "Flows" },
  { label: "matrices", value: "Matrices" },
  { label: "string suffix structures", value: "String Suffix Structures" },
  { label: "graph matchings", value: "Graph Matchings" },
  { label: "fft", value: "FFT" },
  { label: "meet-in-the-middle", value: "Meet In The Middle" },
  { label: "ternary search", value: "Ternary Search" },
  { label: "expression parsing", value: "Expression Parsing" },
];